# Programming Assignment 5
---
**Author:** Caleb Bush*
**Version:** 1.0  
**Semester:** Spring 2024 

This *notebook* contains my solution(s) to **Programming Assignment 5**

### Problem 1 – Language Translator

In [14]:
import numpy as np
import random

In [6]:
EngtoGer = {"myself":"mich",
            "yourself":"dich",
            "our":"unser",
            "long":"lang",
            "large":"groß",
            "small":"klein",
            "how":"wie",
            "where":"wo",
            "what":"was",
            "no":"nein",
            "not":"nicht",
            "here":"hier",
            "there":"da",
            "because":"weil",
            "between":"zwischen",
            "under":"unter",
            "with":"mit",
            "already":"schon",
            "then":"dann",
            "we":"wir"
           }
prompt = input("Enter a word to translate from English to German (enter Q to stop):")
while prompt!="Q":
    prompt_upper=prompt.upper()
    if prompt in EngtoGer:
        translation = EngtoGer[prompt]
        print(f'The German word for {prompt.upper()} is {translation.upper()}.')
    else:
        print(f'The German word for {prompt.upper()} is not in the dictionary.')
    prompt = input("Enter a word to translate from English to German (enter Q to stop):")

Enter a word to translate from English to German (enter Q to stop): here


The German word for HERE is HIER.


Enter a word to translate from English to German (enter Q to stop): the


The German word for THE is not in the dictionary.


Enter a word to translate from English to German (enter Q to stop): Q


### Problem 2 – Translating Morse Code

In [1]:
morsecode_dict = {
    'A': '.-', 'B': '-...', 'C': '-.-.', 'D': '-..', 'E': '.', 'F': '..-.', 'G': '--.', 'H': '....', 
    'I': '..', 'J': '.---', 'K': '-.-', 'L': '.-..', 'M': '--', 'N': '-.', 'O': '---', 'P': '.--.', 
    'Q': '--.-', 'R': '.-.', 'S': '...', 'T': '-', 'U': '..-', 'V': '...-', 'W': '.--', 'X': '-..-', 
    'Y': '-.--', 'Z': '--..',
    '0': '-----', '1': '.----', '2': '..---', '3': '...--', '4': '....-', '5': '.....', 
    '6': '-....', '7': '--...', '8': '---..', '9': '----.'
}

sentence = input("Enter a message to translate to Morse Code (enter lowercase 'q' to quit): ")
while sentence != "q":
    translation = ''
    for char in sentence.upper():
        if char in morsecode_dict:
            translation += morsecode_dict[char] + ' '
        elif char == ' ':
            translation += '/ ' 
    
    print("Morse Code translation:", translation.strip())
    
    sentence = input("Enter a message to translate to Morse Code (enter lowercase 'q' to quit): ")
    

Enter a message to translate to Morse Code (enter lowercase 'q' to quit):  Hello there


Morse Code translation: .... . .-.. .-.. --- / - .... . .-. .


Enter a message to translate to Morse Code (enter lowercase 'q' to quit):  q


###  Problem 3 – Comparing Minors/Majors

In [13]:
data_sci = {'BUSA103','BUSA245','BUSA346','CS150','DS160','DS300','DS450','MATH205','MATH215','MATH430','ECON410'}
analytics = {'BUSA103','BUSA245','BUSA346','CS150','DS160','DS300'}
com_sci = {'CS130','CS131','CS215'}
admin = {'BUSA103','BUSA203','BUSA301','BUSA305'}

i = analytics.intersection(admin)
print(f'i. The overlap in courses for the two minors are: {i}.')

ii = admin.union(com_sci)
print(f'ii. The classes needed for minoring in both are: {ii}.')

iii = admin-analytics
print(f'iii. The classes that are in the Business Admin minor but not in the Business Analytics minor are: {iii}')

iv = com_sci.isdisjoint(data_sci)
print(iv)

v = analytics.issubset(data_sci)
print(v)

i. The overlap in courses for the two minors are: {'BUSA103'}.
ii. The classes needed for minoring in both are: {'BUSA203', 'CS131', 'BUSA301', 'CS130', 'BUSA305', 'BUSA103', 'CS215'}.
iii. The classes that are in the Business Admin minor but not in the Business Analytics minor are: {'BUSA301', 'BUSA305', 'BUSA203'}
True
True


### Problem 4 – Working with NumPy

In [ ]:
num1 = np.random.randint(0,21, size=(5,5))
num2 = np.random.randint(0,21, size=(5,5))

In [18]:
num1

array([[ 6,  8, 18, 17, 12],
       [10,  1,  5, 16, 10],
       [ 9, 10,  4, 19, 13],
       [ 8,  6, 19, 20,  2],
       [14, 18,  6,  6,  4]])

In [19]:
num2

array([[14,  7, 20,  8,  5],
       [10, 12,  6, 11,  7],
       [ 8,  2, 15, 19,  1],
       [13,  7,  7, 16, 13],
       [16,  4, 10,  2, 10]])

In [25]:
m_product = np.matmul(num1,num2)
print(f'The matrix product is: {m_product}')
d_product = np.dot(num1.flatten(),num2.flatten())
print(f'The dot product is: {d_product}')

The matrix product is: [[721 341 677 774 445]
 [558 244 493 462 370]
 [713 376 563 588 496]
 [616 314 641 815 381]
 [566 384 560 528 320]]
The dot product is: 2643


In [26]:
det_num1 = np.linalg.det(num1)
print(f'The determinate for num1 is: {det_num1}')
inv_num1 = np.linalg.inv(num1)
print(f'The inverse for num1 is: {inv_num1}')
det_num2 = np.linalg.det(num2)
print(f'The determinate for num2 is: {det_num2}')
inv_num2 = np.linalg.inv(num2)
print(f'The inverse for num2 is: {inv_num2}')

The determinate for num1 is: -405197.9999999996
The inverse for num1 is: [[-0.02131797  0.12414178 -0.09170825 -0.01125376  0.05727817]
 [-0.00376112 -0.09641212  0.06995099  0.00750744  0.02121926]
 [ 0.06388975  0.01044428 -0.07013855  0.00108095  0.00962986]
 [-0.05954126 -0.03414627  0.08375165  0.05979299 -0.03809989]
 [ 0.08501523  0.03491133 -0.01422021 -0.08570625 -0.0032552 ]]
The determinate for num2 is: -122116.00000000004
The inverse for num2 is: [[-1.97942940e-01  1.18280979e-01  1.42716761e-01 -1.81565069e-01
   2.37937699e-01]
 [ 4.51701661e-02  9.72845491e-02 -5.08532870e-02 -2.19463461e-02
  -5.70686888e-02]
 [ 1.55000164e-01 -8.74905827e-02 -6.79026499e-02  7.69759900e-02
  -1.09535196e-01]
 [-5.18850929e-02  1.66071604e-02  5.95008025e-02  6.35461365e-03
   1.06456156e-04]
 [ 1.54017492e-01 -1.43994235e-01 -1.52003014e-01  2.21035737e-01
  -1.48358937e-01]]


In [27]:
ID1 = np.linspace(0, 1, 20)
ID2 = np.linspace(1, 2, 20)

In [28]:
ID1

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [29]:
ID2

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [34]:
combined_array = np.concatenate((ID1, ID2))
print(f'Combined Array: {combined_array}')
reshaped_array = combined_array.reshape(10, 4)
print(f'Reshaped Array: {reshaped_array}')

Combined Array: [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.         1.         1.05263158 1.10526316 1.15789474
 1.21052632 1.26315789 1.31578947 1.36842105 1.42105263 1.47368421
 1.52631579 1.57894737 1.63157895 1.68421053 1.73684211 1.78947368
 1.84210526 1.89473684 1.94736842 2.        ]
Reshaped Array: [[0.         0.05263158 0.10526316 0.15789474]
 [0.21052632 0.26315789 0.31578947 0.36842105]
 [0.42105263 0.47368421 0.52631579 0.57894737]
 [0.63157895 0.68421053 0.73684211 0.78947368]
 [0.84210526 0.89473684 0.94736842 1.        ]
 [1.         1.05263158 1.10526316 1.15789474]
 [1.21052632 1.26315789 1.31578947 1.36842105]
 [1.42105263 1.47368421 1.52631579 1.57894737]
 [1.63157895 1.68421053 1.73684211 1.78947368]
 [1.84210526 1.89473684 1.94736842 2.        ]]
